### ISSUE TITLE
how to use it with arduino ide

### ISSUE THREAD

**Issue by ninjaWw** [wagiminator/CH552-DAPLink#1]
"Of course, it also works with the [SAMD DevBoards](https://github.com/wagiminator/SAMD-Development-Boards) in the Arduino IDE (Tools -> Programmer -> Generic CMSIS-DAP)."

"Generic CMSIS-DAP" cannot be found in arduino ide, is it because "SAMD-Development-Boards" is not updated? I hope you can introduce in detail how to use it with arduino ide. Thank you very much.

**Comment by wagiminator** [comment]
Mmmh, did you install the ArduinoCore from the link above?

**Comment by ninjaWw** [comment]
I have installed ArduinoCore in the link, but I see that it was updated last two years ago, so I wonder if you did not update the latest daplink.
________________________________
发件人: Stefan Wagner ***@***.***>
发送时间: Saturday, November 25, 2023 8:01:45 PM
收件人: wagiminator/CH552-DAPLink ***@***.***>
抄送: ninjaWw ***@***.***>; Author ***@***.***>
主题: Re: [wagiminator/CH552-DAPLink] how to use it with arduino ide (Issue #1)


Mmmh, did you install the ArduinoCore from the link above?

―
